mentecobre/urls.py
from django.urls import path, re_path


from .views import base

urlpatterns = [
    path('', base.HomeView.as_view(), name='home'),
    path('glosario', base.GlossaryView.as_view(), name='glossary'),
    path('juegos', base.CopperHopperView.as_view(), name='games'),
    path('categorías', base.CategoryListView.as_view(), name='category'),
    path('traducciones', base.TranslateView.as_view(), name='translate'),
    path('revisiones', base.ReviewView.as_view(), name='review'),
    path('rerevisiones', base.RereviewView.as_view(), name='rereview'),
    path('gregorio', base.GregorioView.as_view(), name='gregorio'),
    path('problemasCopper', base.CopperProblemView.as_view(), name='copperproblem'),
    path('cambios', base.ChangesView.as_view(), name='changes'),
    path('cambios/listadocopper', base.CopperListView.as_view(), name='copperlist'),
    path('perfil', base.ProfileView.as_view(), name='profile'),
    path('perfil/<username>/', base.ProfileView.as_view(), name='user-profile'),
    path('login', base.GlossaryView.as_view(), name='login'),
    path('testorden',base.TestOrderView.as_view(),name='test-order')
]

sirayastein/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mentecobre.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler400 = 'mentecobre.views.errors.error_400'
handler403 = 'mentecobre.views.errors.error_403'
handler404 = 'mentecobre.views.errors.error_404'
handler500 = 'mentecobre.views.errors.error_500'

mentecobre/models.py
from django.db import models


from login_app.models import CustomUser, Universe
# Create your models here.



class Articles(models.Model):
    typeOptions = (('CU', 'Cultura'), ('EVT', 'Eventos y eras'), ('FDV', 'Formas de vida'), ('LIB', 'Libros'),
                    ('LOC', 'Localizaciones'), ('MG', 'Magia'), ('PJ', 'Personajes'), ('OBJ', 'Objetos y materiales'),
                    ('ORG', 'Organización'), ('FAM', 'Familia'), ('MUL', 'Multimedia'), ('WIKI', 'Wiki/otros'),
                    ('DIS', 'Disambiguación'), ('RD', 'Redirección'), ('SUB', 'Subpágina'),)

    priorityOptions = (('1', 'Alta'), ('2', 'Media'), ('3', 'Baja'), ('4', 'TBD'), ('5', 'Siraya'),)

    pageidEn = models.IntegerField(null=True, blank=True, verbose_name='ID Coppermind en inglés')
    pageidEs = models.IntegerField(null=True, blank=True, verbose_name='ID Coppermind en español')
    titleEn = models.CharField(max_length=200, null=True, blank=True, verbose_name='Título inglés')
    titleEs = models.CharField(max_length=200, null=True, blank=True, verbose_name='Título español')
    type = models.CharField(max_length=4, choices=typeOptions, null=True, blank=True, verbose_name='Tipo de artículo')
    priority = models.CharField(max_length=1, choices=priorityOptions, null=True, blank=True,verbose_name='Prioridad')
    translator = models.ForeignKey(CustomUser, on_delete=models.DO_NOTHING, null=True, blank=True,
                                   limit_choices_to={'groups__name': "Traductores"}, related_name='translator',
                                   verbose_name='Traductor')
    assignedDate = models.DateField(null=True, blank=True, verbose_name='Fecha asignado traductor')
    translated = models.BooleanField(default=False,verbose_name='Traducido')
    translatedDate = models.DateField(null=True, blank=True,verbose_name='Fecha traducido')
    reviewer = models.ForeignKey(CustomUser, models.DO_NOTHING, null=True, blank=True,
                                 limit_choices_to={'groups__name': "Revisores"}, related_name='reviewer',
                                 verbose_name='Revisor')
    reviewed = models.BooleanField(default=False, verbose_name='Revisado')
    reviewerassignedDate = models.DateField(null=True, blank=True, verbose_name='Fecha asignado revisor')
    reviewedDate = models.DateField(null=True, blank=True, verbose_name='Fecha revisado')
    gregorio = models.ForeignKey(CustomUser, models.DO_NOTHING, null=True, blank=True,
                                 limit_choices_to={'is_superuser': True}, related_name='gregorio')
    engregoriado = models.BooleanField(default=False)
    notes = models.TextField(null=True, blank=True, verbose_name='notas')
    universe = models.ForeignKey(Universe, models.DO_NOTHING, null=True, blank=True, related_name='article_universe',
                                 verbose_name='Universo')
    urldrive = models.URLField(null=True, blank=True)
    urlEn = models.URLField(null=True, blank=True, verbose_name='Enlace Coppermind en inglés')
    urlEs = models.URLField(null=True, blank=True, verbose_name='Enlace Coppermind en español')
    linkcopperen = models.BooleanField(default=False, verbose_name='Enlazada con la Coppermind en inglés')
    problemCopper = models.TextField(null=True, blank=True, verbose_name='Problemas de la Copper')

    def __str__(self):
        return str(self.titleEs)

    def get_absolute_url(self):
        return reverse('titleEs', args=[str(self.id)])

    class Meta:
        verbose_name = 'Artículo'
        verbose_name_plural = 'Artículos'

class Glossary(models.Model):

    wordEn = models.CharField(max_length=200, verbose_name='Palabra inglés')
    wordEs = models.CharField(max_length=200, null=True, blank=True, verbose_name='Palabra español')
    universe = models.ForeignKey(Universe, models.DO_NOTHING, null=True, blank=True, related_name='glossary_universe',
                                 verbose_name='Universo')
    urlEn = models.URLField(max_length=2000, null=True, blank=True, verbose_name='Enlace Coppermind en inglés')
    urlEs = models.URLField(max_length=2000, null=True, blank=True, verbose_name='Enlace Coppermind en español')

    def __str__(self):
        return str(self.wordEs)

    def get_absolute_url(self):
        return reverse('wordEs', args=[str(self.id)])

    class Meta:
        verbose_name = 'Glosario'
        verbose_name_plural = 'Glosario'


class Category(models.Model):

    catEn = models.CharField(max_length=200, verbose_name='Categoría inglés')
    catEs = models.CharField(max_length=200, null=True, blank=True, verbose_name='Categoría español')
    urlEn = models.URLField(max_length=2000, null=True, blank=True, verbose_name='Enlace Coppermind en inglés')
    urlEs = models.URLField(max_length=2000, null=True, blank=True, verbose_name='Enlace Coppermind en español')

    def __str__(self):
        return str(self.catEs)

    def get_absolute_url(self):
        return reverse('catEs', args=[str(self.id)])

    class Meta:
        verbose_name = 'Categoría'
        verbose_name_plural = 'Categorías'

mentecobre/forms.py
from django import forms

class AssignArticleForm(forms.Form):
    articleUniverseID = forms.IntegerField()

class ChangesForm(forms.Form):
    start_date = forms.DateField(widget=forms.DateInput(attrs=dict(type='date')), label='Fecha inicial')
    end_date = forms.DateField(widget=forms.DateInput(attrs=dict(type='date')), label='Fecha final')

class GregorioForm(forms.Form):
    username = forms.CharField(required=True)
    status = forms.CharField(required=True)

class CopperListForm(forms.Form):
    CHOICES = (('Es', 'Español'), ('En', 'Inglés'),)
    language = forms.ChoiceField(choices=CHOICES, required=True, label='Idioma')

class ProblemArticleForm(forms.Form):
    articleID = forms.IntegerField()

class ReReviewArticleForm(forms.Form):
    articleID = forms.IntegerField()

class ReviewArticleForm(forms.Form):
    articleID = forms.IntegerField()
    notes = forms.CharField(widget=forms.Textarea, required=False)
    linkcoppperen = forms.BooleanField()

class TranslateArticleForm(forms.Form):
    articleID = forms.IntegerField()
    notes = forms.CharField(widget=forms.Textarea, required=False)

mentecobre/views.py
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import render, redirect
from django.views import View
from django.views.decorators.clickjacking import xframe_options_exempt


from datetime import date

from .forms import TranslateArticleForm, AssignArticleForm, ReviewArticleForm
from .models import Glossary, Articles
from .manager import TranslateManager, ReviewManager
from login_app.models import Universe


# Create your views here.

class GlossaryView(View):

    @xframe_options_exempt
    def get(self, request):
        search = request.GET.get("q", None)
        if search is not None:
            query = search
            object_list = Glossary.objects.filter(
                Q(wordEn__icontains=query) | Q(wordEs__icontains=query)
            )

        else:
            object_list = None

        return render(
            request,
            'mentecobre/glossary.html',
            context={"object_list": object_list}
        )

class ReviewView(View):
    def get(self, request):
        user = request.user
        userid = user.id
        username = user.username
        universes = user.universe

        article_assigned = ReviewManager.get_assigned_articles_for_user(userid)
        list_next_articles_to_assign = ReviewManager().get_list_next_article_to_assign(universes, userid)

        form = ReviewArticleForm()

        return render(
            request,
            'mentecobre/reviews.html',
            context={"user": username, "article_assigned": article_assigned,
                     "next_articles_to_assign": list_next_articles_to_assign, "form":form},
        )

    def post(self, request):
        if 'form-review' in request.POST:
            form = ReviewArticleForm(request.POST)
            if form.is_valid():
                article_id = form.cleaned_data["articleID"]
                article_notes = form.cleaned_data["notes"]
                article_translated_date = date.today()
                Articles.objects.filter(pk=article_id).update(reviewed=True, reviewedDate=article_translated_date,
                                                              notes=article_notes, linkcopperen=True)
        elif 'form-assign-review' in request.POST:
            form = AssignArticleForm(request.POST)
            if form.is_valid():
                universe_id = form.cleaned_data["articleUniverseID"]
                userid = request.user.id
                assigned_date = date.today()

                article_assigned = ReviewManager.get_assigned_articles_for_user(userid)
                if article_assigned:
                    messages.error(request, 'Ya tienes un artículo asignado')

                else:
                    universe = Universe.objects.get(id=universe_id)
                    ReviewManager().assign_article_to_user(universe, userid, assigned_date)
                    messages.info(request, 'Se ha asignado el artículo con éxito')

        return redirect('review')

class TranslateView(View):
    def get(self, request):
        user = request.user
        userid = user.id
        username = user.username
        universes = user.universe

        article_assigned = TranslateManager.get_assigned_articles_for_user(userid)
        list_next_articles_to_assign = TranslateManager().get_list_next_article_to_assign(universes)


        return render(
            request,
            'mentecobre/translations.html',
            context={"user": username, "article_assigned": article_assigned,
                     "next_articles_to_assign": list_next_articles_to_assign},
        )

    def post(self,request):
        if 'form-translate' in request.POST:
            form = TranslateArticleForm(request.POST)
            if form.is_valid():
                article_id =form.cleaned_data["articleID"]
                article_notes =form.cleaned_data ["notes"]
                article_translated_date = date.today()
                Articles.objects.filter(pk=article_id).update(translated=True, translatedDate=article_translated_date,
                                                              notes=article_notes)
        elif 'form-assign-translate' in request.POST:
            form = AssignArticleForm(request.POST)
            if form.is_valid():
                universe_id = form.cleaned_data["articleUniverseID"]
                userid = request.user.id
                assigned_date = date.today()


                article_assigned = TranslateManager.get_assigned_articles_for_user(userid)
                if article_assigned:
                    messages.error(request, 'Ya tienes un artículo asignado')

                else:
                    universe = Universe.objects.get(id=universe_id)
                    TranslateManager().assign_article_to_user(universe, userid, assigned_date)
                    messages.info(request, 'Se ha asignado el artículo con éxito')

        return redirect('translate')

mentecobre/views/errors.py
from django.shortcuts import render

def error_400(request, exception):
    return render(request, 'error/400.html', status=400)

def error_403(request, exception):
    return render(request, 'error/403.html', status=403)

def error_404(request, exception):
    return render(request, 'error/404.html', status=400)

def error_500(request):
    return render(request, 'error/500.html', status=500)

sirayastein/templates/mentecobre/category.html
{% extends "../base/base.html" %}

{% block content %}
<div id="content-wrapper" class="d-flex flex-column">
    <div class="container-fluid">
            <h1 class="text-white text-center">Categoría</h1>
            <p class="text-white text-center"> Lista de categorías.</p>
	</div>
    <div class="container-fluid">
		{% if category_list %}
    		<table id="categoryDataTable" class="table table-bordered cell-border w-50 text-center">
				<thead>
					<tr>
						<th scope="col">Inglés</th>
						<th scope="col">Español</th>
					</tr>
				</thead>
				<tbody>
					{%for object in category_list %}
						<tr>
							<td><a href={{object.urlEn}} target="_blank" rel="noopener noreferrer"> {{object.catEn}} </a></td>
							<td><a href={{object.urlEs}} target="_blank" rel="noopener noreferrer"> {{object.catEs}} </a></td>
						</tr>
					{%endfor%}
				</tbody>
			</table>
		{% else %}
				<p class="text-white text-center"> No hay lista de categorías </p>
		{% endif %}
	</div>
</div>

{% endblock %}

sirayastein/templates/mentecobre/changesCopper.html
{% extends "../base/base.html" %}

{% block content %}
<div id="content-wrapper" class="d-flex flex-column">

    <div class="split left">
        <div class="centered">
            <div class="card" style="background-color: rgba(255, 255, 255, 0.5)">
               <div class="card-header bg-cosmere" id="headingcambios">
                  <h5 class="mb-0 text-white">
                      Sacar cambios
                  </h5>
               </div>
               <div class="card-body">
                   <form method="POST" id="form-copper-changes">
                       {% csrf_token %}
                       {{form_changes.as_p }}
                       <input name="form-copper-changes" type="submit" value="Descargar" class="assign-button">
                   </form>
               </div>
            </div>
        </div >

    </div>
    <div class="split right">
      <div class="centered">
         <div class="card"  style="background-color: rgba(255, 255, 255, 0.5)">
           <div class="card-header bg-cosmere" id="headinglists">
                <h5 class="mb-0 text-white">
                      Sacar Listados de la Coppermind
                </h5>
             </div>
           <div class="card-body">
                <form method="POST" id="form-copper-list">
                       {% csrf_token %}
                       {{form_copperlist.as_p }}
                       <input name="form-copper-list" type="submit" value="Sacar listado" class="assign-button">
               </form>
           </div>
         </div>
      </div>
    </div>

</div>


{% endblock %}

sirayastein/templates/mentecobre/reviews.html
{% extends "../base/base.html" %}
{% load static %}
{% block content %}

<div id="content-wrapper" class="d-flex flex-column">
	<div class="container-fluid">

		<!-- Page Heading -->
		<div>
                      <h1 class="text-white text-center">Revisión</h1>

        </div>

		<div class="row">
			<div class = "col-lg-6 mb-4">
				<div class="card shadow mb-4 bg-dark-subtle">
					<div class="card-header py-3 bg-cosmere">
						<h6 class="fw-bold m-0 text-center">
							¡Hola, {{user}}! El artículo en el que estás trabajando es
						</h6>
					</div>
					<div class ="card-body">
						{% if article_assigned %}
							<div class="table-form">
								<div class="thead-form">
										<div class="th-form">Título En</div>
										<div class="th-form">Título Es</div>
										<div class="th-form">Universo</div>
										<div class="th-form">Traductor</div>
										<div class="th-form">Notas</div>
										<div class="th-form">Enlazado a la Copper</div>
										<div class="th-form"></div>
								</div>
								<div class="tbody-form">
									{% for article_item in article_assigned %}
									<form method="POST" id="form-review"  name="form-review" class="tr-form">
										<div class="td-form">
											<a style="color:black" href={{article_item.urlEn}} target="_blank" rel="noopener noreferrer">
												{{article_item.titleEn}}
											</a>
										</div>
										<div class="td-form">
											<a style="color:black" href={{article_item.urlEs}} target="_blank" rel="noopener noreferrer">
												{{article_item.titleEs}}
											</a>
										</div>
										<div class="td-form">{{article_item.universe.universe}}</div>
										<div class="td-form">{{article_item.translator.username}}</div>
										<div class="td-form">
											{% csrf_token %}
											<input type="hidden" id="id_articleID" name="articleID" value={{article_item.id}}>

											<textarea name="notes" id="id_notes" placeholder="¿Algo que comentar?">{{article_item.notes}}</textarea>
										</div>
										<div class="td-form" style="text-align: center;">
												<div class="form-switch">
												{% if article_item.linkcopperen == True %}
													<input type="checkbox" class="form-check-input" id="id_linkcoppperen" name="linkcoppperen" checked required>
												{% else %}
													<input type="checkbox" class="form-check-input" id="id_linkcoppperen" name="linkcoppperen" required>
												{% endif %}
												</div>
										</div>
										<div class="td-form">
											<input name="form-review" type="submit" value="Marcar como revisado" class="assign-button">
										</div>

									</form>

								{% endfor %}
								</div>
							</div>

						{% else %}
							<p class="text-center">Oh vaya, no parece que estés trabajando ahora en nada</p>
							<p class="text-center"><img src="{% static 'img/travoltar.gif' %}" width="250" alt="nothing" /></p>
						{% endif %}
					</div>
				</div>

			</div>
			<div class = "col-lg-6 mb-4">
				<div class="card shadow mb-4 bg-dark-subtle">
					<div class="card-header py-3 bg-cosmere">
						<h6 class="fw-bold m-0 text-center">
							El siguiente artículo disponible es
						</h6>
					</div>
					<div class ="card-body">
						<table class="table">
							<thead>
							    <tr>
								    <th class="th-articles">Inglés</th>
								    <th class="th-articles">Español</th>
								    <th class="th-articles">Universo</th>
									<th class="th-articles">Traductor</th>
								  <th class="th-articles"></th>
								</tr>
							</thead>
							<tbody>
							{% for next_articles_to_assign_item in next_articles_to_assign %}
							<tr>
							<td class="td-articles"><a style="color:black" href={{next_articles_to_assign_item.urlEn}} target="_blank" rel="noopener noreferrer">{{next_articles_to_assign_item.titleEn}}</a></td>
							<td class="td-articles"><a style="color:black" href={{next_articles_to_assign_item.urlEs}} target="_blank" rel="noopener noreferrer">{{next_articles_to_assign_item.titleEs}}</a></td>
							<td class="td-articles">{{next_articles_to_assign_item.universe.universe}}</td>
							<td class="td-articles">{{next_articles_to_assign_item.translator}}</td>
							<td class="td-articles">
							<form method="POST" id="form-assign-review">
								{% csrf_token %}
								<input type="hidden" id="id_articleUniverseID" name="articleUniverseID" value={{next_articles_to_assign_item.universe.id}}>
								<input name="form-assign-review" type="submit" value="Asignar" class="assign-button">
							</form>
							</td>
							</tr>
						{% endfor %}
							</tbody>
						</table>

					</div>
				</div>

			</div>

		</div>

		<div>
			<h6 class="text-white text-center">Recuerda, si tienes alguna duda sobre el proceso, puedes consultarlo aquí:
				<a class="text-info" href="https://sites.google.com/view/ayuda-traduccion-coppermind/inicio" target="_blank" rel="noopener noreferrer">Página de Ayuda</a>
			</h6>
		</div>
		
</div>
</div>
{% endblock %}

sirayastein/templates/mentecobre/traducciones.html
{% extends "../base/base.html" %}
{% load static %}
{% block content %}

<div id="content-wrapper" class="d-flex flex-column">
	<div class="container-fluid">

		<!-- Page Heading -->
		<div>
                      <h1 class="text-white text-center">Traducción</h1>

        </div>

		<div class="row">
			<div class = "col-lg-6 mb-4">
				<div class="card shadow mb-4 bg-dark-subtle">
					<div class="card-header py-3 bg-cosmere">
						<h6 class="fw-bold m-0 text-center">
							¡Hola, {{user}}! El artículo en el que estás trabajando es
						</h6>
					</div>
					<div class ="card-body">
						{% if article_assigned %}
							<div class="table-form">
								<div class="thead-form">
										<div class="th-form">Título En</div>
										<div class="th-form">Título Es</div>
										<div class="th-form">Universo</div>
										<div class="th-form">Drive</div>
										<div class="th-form">Notas</div>
										<div class="th-form"></div>
								</div>
								<div class="tbody-form">
									{% for article_item in article_assigned %}
									<form method="POST" id="form-translate"  name="form-translate" class="tr-form">
										<div class="td-form">
											<a style="color:black" href={{article_item.urlEn}} target="_blank" rel="noopener noreferrer">
												{{article_item.titleEn}}
											</a>
										</div>
										<div class="td-form">
											<a style="color:black" href={{article_item.urlEs}} target="_blank" rel="noopener noreferrer">
												{{article_item.titleEs}}
											</a>
										</div>
										<div class="td-form">{{article_item.universe.universe}}</div>
										<div class="td-form">
											{% if article_item.urldrive is not null %}
												<a href={{article_item.urldrive}} target="_blank" rel="noopener noreferrer"><button class="btn btn-cosmere">Archivo Drive</button></a>
											{% else %}
												<button class="btn btn-cosmere" disabled>Archivo Drive</button>
											{% endif %}
										</div>
										<div class="td-form">

											{% csrf_token %}
											<input type="hidden" id="id_articleID" name="articleID" value={{article_item.id}}>
											<textarea name="notes" id="id_notes" placeholder="¿Algo que comentar?">{{article_item.notes}}</textarea>
										</div>
										<div class="td-form">
											<input name="form-translate" type="submit" value="Marcar como traducido" class="assign-button">
										</div>

									</form>

								{% endfor %}
								</div>
							</div>

						{% else %}
							<p class="text-center">Oh vaya, no parece que estés trabajando ahora en nada</p>
							<p class="text-center"><img src="{% static 'img/travoltar.gif' %}" width="250" alt="nothing" /></p>
						{% endif %}
					</div>
				</div>

			</div>
			<div class = "col-lg-6 mb-4">
				<div class="card shadow mb-4 bg-dark-subtle">
					<div class="card-header py-3 bg-cosmere">
						<h6 class="fw-bold m-0 text-center">
							El siguiente artículo disponible es
						</h6>
					</div>
					<div class ="card-body">
						<table class="table">
							<thead>
							    <tr>
								  <th class="th-articles">Título En</th>
								  <th class="th-articles">Título Es</th>
								  <th class="th-articles">Universo</th>
								  <th class="th-articles"></th>
								</tr>
							</thead>
							<tbody>
							{% for next_articles_to_assign_item in next_articles_to_assign %}
							<tr>
							<td class="td-articles"><a style="color:black" href={{next_articles_to_assign_item.urlEn}} target="_blank" rel="noopener noreferrer">{{next_articles_to_assign_item.titleEn}}</a></td>
							<td class="td-articles"><a style="color:black" href={{next_articles_to_assign_item.urlEs}} target="_blank" rel="noopener noreferrer">{{next_articles_to_assign_item.titleEs}}</a></td>
							<td class="td-articles">{{next_articles_to_assign_item.universe.universe}}</td>
							<td class="td-articles">
							<form method="POST" id="form-assign-translate">
								{% csrf_token %}
								<input type="hidden" id="id_articleUniverseID" name="articleUniverseID" value={{next_articles_to_assign_item.universe.id}}>
								<input name="form-assign-translate" type="submit" value="Asignar" class="assign-button">
							</form>
							</td>
							</tr>
						{% endfor %}
							</tbody>
						</table>

					</div>
				</div>

			</div>

		</div>

		<div>
			<h6 class="text-white text-center">Recuerda, si tienes alguna duda sobre el proceso, puedes consultarlo aquí:
				<a class="text-info" href="https://sites.google.com/view/ayuda-traduccion-coppermind/inicio" target="_blank" rel="noopener noreferrer">Página de Ayuda</a>
			</h6>
		</div>
		
</div>
</div>
{% endblock %}

sirayastein/templates/mentecobre/translations.html
{% extends "../base/base.html" %}
{% load static %}
{% block content %}

<div id="content-wrapper" class="d-flex flex-column">
	<div class="container-fluid">

		<!-- Page Heading -->
		<div>
                      <h1 class="text-white text-center">Traducción</h1>

        </div>

		<div class="row">
			<div class = "col-lg-6 mb-4">
				<div class="card shadow mb-4 bg-dark-subtle">
					<div class="card-header py-3 bg-cosmere">
						<h6 class="fw-bold m-0 text-center">
							¡Hola, {{user}}! El artículo en el que estás trabajando es
						</h6>
					</div>
					<div class ="card-body">
						{% if article_assigned %}
							<div class="table-form">
								<div class="thead-form">
										<div class="th-form">Título En</div>
										<div class="th-form">Título Es</div>
										<div class="th-form">Universo</div>
										<div class="th-form">Drive</div>
										<div class="th-form">Notas</div>
										<div class="th-form"></div>
								</div>
								<div class="tbody-form">
									{% for article_item in article_assigned %}
									<form method="POST" id="form-translate"  name="form-translate" class="tr-form">
										<div class="td-form">
											<a style="color:black" href={{article_item.urlEn}} target="_blank" rel="noopener noreferrer">
												{{article_item.titleEn}}
											</a>
										</div>
										<div class="td-form">
											<a style="color:black" href={{article_item.urlEs}} target="_blank" rel="noopener noreferrer">
												{{article_item.titleEs}}
											</a>
										</div>
										<div class="td-form">{{article_item.universe.universe}}</div>
										<div class="td-form">
											{% if article_item.urldrive is not null %}
												<a href={{article_item.urldrive}} target="_blank" rel="noopener noreferrer"><button type="button" class="btn btn-cosmere">Archivo Drive</button></a>
											{% else %}
												<button type="button" class="btn btn-cosmere" disabled>Archivo Drive</button>
											{% endif %}
										</div>

											<div class="td-form">
												{% csrf_token %}
												<input type="hidden" id="id_articleID" name="articleID" value={{article_item.id}}>
												<textarea name="notes" id="id_notes" placeholder="¿Algo que comentar?">{{article_item.notes}}</textarea>
											</div>
											<div class="td-form">
												<input name="form-translate" type="submit" value="Marcar como traducido" class="assign-button">
											</div>

									</form>

								{% endfor %}
								</div>
							</div>

						{% else %}
							<p class="text-center">Oh vaya, no parece que estés trabajando ahora en nada</p>
							<p class="text-center"><img src="{% static 'img/travoltar.gif' %}" width="250" alt="nothing" /></p>
						{% endif %}
					</div>
				</div>

			</div>
			<div class = "col-lg-6 mb-4">
				<div class="card shadow mb-4 bg-dark-subtle">
					<div class="card-header py-3 bg-cosmere">
						<h6 class="fw-bold m-0 text-center">
							El siguiente artículo disponible es
						</h6>
					</div>
					<div class ="card-body">
						<table class="table">
							<thead>
							    <tr>
								  <th class="th-articles">Título En</th>
								  <th class="th-articles">Título Es</th>
								  <th class="th-articles">Universo</th>
								  <th class="th-articles"></th>
								</tr>
							</thead>
							<tbody>
							{% for next_articles_to_assign_item in next_articles_to_assign %}
							<tr>
							<td class="td-articles"><a style="color:black" href={{next_articles_to_assign_item.urlEn}} target="_blank" rel="noopener noreferrer">{{next_articles_to_assign_item.titleEn}}</a></td>
							<td class="td-articles"><a style="color:black" href={{next_articles_to_assign_item.urlEs}} target="_blank" rel="noopener noreferrer">{{next_articles_to_assign_item.titleEs}}</a></td>
							<td class="td-articles">{{next_articles_to_assign_item.universe.universe}}</td>
							<td class="td-articles">
							<form method="POST" id="form-assign-translate">
								{% csrf_token %}
								<input type="hidden" id="id_articleUniverseID" name="articleUniverseID" value={{next_articles_to_assign_item.universe.id}}>
								<input name="form-assign-translate" type="submit" value="Asignar" class="assign-button">
							</form>
							</td>
							</tr>
						{% endfor %}
							</tbody>
						</table>

					</div>
				</div>

			</div>

		</div>

		<div>
			<h6 class="text-white text-center">Recuerda, si tienes alguna duda sobre el proceso, puedes consultarlo aquí:
				<a class="text-info" href="https://sites.google.com/view/ayuda-traduccion-coppermind/inicio" target="_blank" rel="noopener noreferrer">Página de Ayuda</a>
			</h6>
		</div>
		
</div>
</div>
{% endblock %}